Update shared prototypes
OpenGreenery/OpenGreenery pull request #8
Opened 2021-08-03 19:16 UTC by Alexander-Degtyar

2021-08-22 09:20 UTC, ValentiWorkLearning approved these changes
Ship it 😁

2021-08-23 10:10 UTC, Alexander-Degtyar commented
> Ship it 😁

Thank you very much @ValentiWorkLearning. We appreciate it.

2021-08-24 11:44 UTC, seclerp requested changes

2021-08-24 11:44 UTC, seclerp commented on src/shared/protos/actions.proto
> +  open_greenery.common.VentilationState = 2;
Field name is missing

2021-08-24 11:44 UTC, seclerp commented on src/shared/protos/actions.proto
> +  open_greenery.common.SoilIrrigationMode mode = 1;
Adjust correct field numbers, please

2021-09-15 12:56 UTC, Alexander-Degtyar commented
@seclerp, fixed.

2021-09-16 16:24 UTC, seclerp approved these changes

2021-09-16 16:24 UTC, merged